language: go
go:
  - "1.12"
  - "1.13"
  - tip
script:
  - go build
  - go test ./... -v -race -cover -coverprofile=coverage.txt -covermode=atomic
  - go test -bench=. -run=^$ -cpu=4 -benchmem
after_script:
  - bash <(curl -s https://codecov.io/bash)
