
name: Publish website to GitHub Pages
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Setup ssh
      env:
        SSH_PATH: /root/.ssh
      run: |
        eval $(ssh-agent)
        ssh-add - <<< "${{ secrets.DEPLOY_SSH_KEY }}"
        eval$(ssh -o StrictHostKeyChecking=no)
        ssh-keyscan -t rsa github.com
    - name: Copy Files
      uses: actions/checkout@v2
    - name: Setup Git
      run: |
        git config --global user.name "$GITHUB_ACTOR"
        git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
    - name: install
      run: cd website/src && yarn install
    - name: build
      run: cd website/src && yarn build
    - name: Publish website
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: cd website/src && GIT_USER="$GITHUB_ACTOR:$GITHUB_TOKEN" CURRENT_BRANCH=master yarn run publish-gh-pages
    - name: Publish website
      run: cd website/src && GIT_USER=$GITHUB_ACTOR CURRENT_BRANCH=master USE_SSH=true yarn run publish-gh-pages
